

import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author profslpa
 */
public class tela1 extends javax.swing.JFrame {
    boolean contBlue=false,contRed=false,contDraw=false;
    String cor;
    GameClassic game;
    int cont = 50;
    
     
   
    public tela1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btninicio = new javax.swing.JButton();
        lblescolha = new javax.swing.JLabel();
        btn_redClassic = new javax.swing.JButton();
        lbltxt = new javax.swing.JLabel();
        lblgifazul = new javax.swing.JLabel();
        btn_drawClassic = new javax.swing.JButton();
        btn_bluelClassic = new javax.swing.JButton();
        lblgif = new javax.swing.JLabel();
        lbl_clique = new javax.swing.JLabel();
        lbldadov1 = new javax.swing.JLabel();
        lbldiceblue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        btninicio.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        btninicio.setForeground(new java.awt.Color(51, 51, 51));
        btninicio.setText("INICIO");
        btninicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninicioActionPerformed(evt);
            }
        });
        getContentPane().add(btninicio);
        btninicio.setBounds(10, 10, 45, 20);

        lblescolha.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblescolha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblescolha);
        lblescolha.setBounds(110, 170, 280, 50);

        btn_redClassic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botaoVERMELHOsf (1).png"))); // NOI18N
        btn_redClassic.setBorderPainted(false);
        btn_redClassic.setContentAreaFilled(false);
        btn_redClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redClassicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_redClassic);
        btn_redClassic.setBounds(70, 220, 110, 40);

        lbltxt.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lbltxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbltxt);
        lbltxt.setBounds(60, 0, 370, 110);
        getContentPane().add(lblgifazul);
        lblgifazul.setBounds(310, 70, 120, 110);

        btn_drawClassic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botaoEMPATEsf (1).png"))); // NOI18N
        btn_drawClassic.setBorderPainted(false);
        btn_drawClassic.setContentAreaFilled(false);
        btn_drawClassic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_drawClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_drawClassicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_drawClassic);
        btn_drawClassic.setBounds(190, 290, 100, 30);

        btn_bluelClassic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botaoAZULsf (1).png"))); // NOI18N
        btn_bluelClassic.setBorderPainted(false);
        btn_bluelClassic.setContentAreaFilled(false);
        btn_bluelClassic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_bluelClassic.setHideActionText(true);
        btn_bluelClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bluelClassicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bluelClassic);
        btn_bluelClassic.setBounds(310, 220, 110, 40);
        getContentPane().add(lblgif);
        lblgif.setBounds(80, 70, 120, 110);
        getContentPane().add(lbl_clique);
        lbl_clique.setBounds(160, 10, 160, 30);

        lbldadov1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/n1-vermelho.png"))); // NOI18N
        getContentPane().add(lbldadov1);
        lbldadov1.setBounds(80, 70, 110, 100);

        lbldiceblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/n1-azul.png"))); // NOI18N
        getContentPane().add(lbldiceblue);
        lbldiceblue.setBounds(320, 70, 100, 100);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoDD.jpeg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, -20, 500, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bluelClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bluelClassicActionPerformed
        jogarDado("blue");
        contBlue = true;
        lblescolha.setText("Blue foi sua escolha");
        
    }//GEN-LAST:event_btn_bluelClassicActionPerformed

    private void btn_redClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redClassicActionPerformed
        jogarDado("red");
        contRed = true;
        lblescolha.setText("Red foi sua escolha");
    }//GEN-LAST:event_btn_redClassicActionPerformed

    private void btn_drawClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_drawClassicActionPerformed
         jogarDado("draw");
         contDraw = true;
         lblescolha.setText("Draw foi sua escolha");
    }//GEN-LAST:event_btn_drawClassicActionPerformed

    private void btninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninicioActionPerformed
       new telaInicial().setVisible(true);
       dispose();
    }//GEN-LAST:event_btninicioActionPerformed

    public void jogarDado(String cor){
        lbldadov1.setVisible(false);
        ImageIcon gif1 = new ImageIcon("src/img/dadogifnovo.gif");
        lblgif.setIcon(gif1);
        lblgif.setVisible(true);

        lbldiceblue.setVisible(false);
        ImageIcon gif2 = new ImageIcon("src/img/gifdadoazul.gif");
        lblgifazul.setIcon(gif2);
        lblgifazul.setVisible(true);
        
        game = new GameClassic(lblgif,lblgifazul,lbltxt,cor,cont++);
        game.start();
        lbl_clique.setText("");
        verificarResultado();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bluelClassic;
    private javax.swing.JButton btn_drawClassic;
    private javax.swing.JButton btn_redClassic;
    private javax.swing.JButton btninicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_clique;
    private javax.swing.JLabel lbldadov1;
    private javax.swing.JLabel lbldiceblue;
    private javax.swing.JLabel lblescolha;
    private javax.swing.JLabel lblgif;
    private javax.swing.JLabel lblgifazul;
    private javax.swing.JLabel lbltxt;
    // End of variables declaration//GEN-END:variables

    private void verificarResultado() {
        
       // if ((contRed  && (game.dadov > game.dadoa)) || (contBlue  && (game.dadov < game.dadoa))) {
      //      lbl_clique.setText("Meus parabens vc venceu!");
       // } else if (contDraw  && (game.dadov == game.dadoa)) {
        //    lbl_clique.setText("Deu empate vc ganhou!");
       // } else {
      //      lbl_clique.setText("nao foi dessa vez");
      //  }
        
        System.out.println("Azul: " + game.dadoa + "Vermelho: " + game.dadov);
    }

}
